### ISSUE TITLE
Lab #1

### ISSUE THREAD

**Issue by els7134** [els7134/ISSEM-Group-24#3]
**Colab notebook link:** https://colab.research.google.com/drive/1GKI4mr00TEBD6l_DCCJSIionL5R8o8as?usp=sharing

**Instructions PDF Link:** https://brightspace.nyu.edu/d2l/common/viewFile.d2lfile/Database/MjQ0OTM4MTg/Lab%201.pdf?ou=372675

**Comment by els7134** [comment]
- [ ] tbd

**Comment by els7134** [comment]
# Task List

### Setup:
- [x] Setup (tasks 1-6)

### Basic Python Questions:
- [x] Task 7
- [x] Task 8
- [x] Task 9
- [x] Task 10

### Basic Cybersecurity Questions:
- [x] Task 11

### Shift Cypher:
- [x] Task 12 - Implement encryption function
- [x] Task 12 - Implement decryption function

### Hashing:
- [x] Task 13
- [x] Task 14
- [x] Task 15

### Submission:
- [ ] Download & submit to brightspace (1 submission per group)

**Comment by shaunbartole** [comment]
> # Task List
> ### Setup:
> * [x]  Setup (tasks 1-6)
> 
> ### Basic Python Questions:
> * [ X]  Task 7
> * [ ]  Task 8
> * [ ]  Task 9
> * [ ]  Task 10
> 
> ### Basic Cybersecurity Questions:
> * [ ]  Task 11
> 
> ### Shift Cypher:
> * [ ]  Task 12 - Implement encryption function
> * [ ]  Task 12 - Implement decryption function
> 
> ### Hashing:
> * [ ]  Task 13
> * [ ]  Task 14
> * [ ]  Task 15
> 
> ### Submission:
> * [ ]  Download & submit to brightspace (1 submission per group)

**Comment by shaunbartole** [comment]
> # Task List
> ### Setup:
> * [x]  Setup (tasks 1-6)
> 
> ### Basic Python Questions:
> * [x]  Task 7
> * [x]  Task 8
> * [x]  Task 9
> * [x]  Task 10
> 
> ### Basic Cybersecurity Questions:
> * [ ]  Task 11
> 
> ### Shift Cypher:
> * [x]  Task 12 - Implement encryption function
> * [x]  Task 12 - Implement decryption function
> 
> ### Hashing:
> * [ ]  Task 13
> * [ ]  Task 14
> * [ ]  Task 15
> 
> ### Submission:
> * [ ]  Download & submit to brightspace (1 submission per group)
